services:
  db:
    image: postgres:16-alpine
    container_name: plasmic-postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: plasmic-axum-leptos
#    environment:
#      RUST_LOG: debug
#      DATABASE_URL: postgres://app_user:app_password@db:5432/app_db
#      BIO_SERVICE_URL: http://bio-service:8000
#    depends_on:
#      - plasmic-postgres
#      - plasmic-llama
#      - plasmic-bio
    ports:
      - "3000:3000"
#    volumes:
#      - .:/usr/src/app
#      - cargo-target:/usr/src/app/target

  llama-service:
    build: ./llama-service
    container_name: plasmic-llama

  bio-service:
    build: ./bio-service
    container_name: plasmic-bio
    environment:
      LLAMA_URL: http://llama-service:8000
    depends_on:
      - llama-service

volumes:
  postgres-data:
  cargo-target:
