services:
  db:
    image: postgres:16-alpine
    container_name: plasmic-postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  llama-service:
    volumes:
      - ./models:/models:ro
    build: ./llama-service
    container_name: plasmic-llama
    ports:
      - "8000:8000"
    environment:
#      MODEL_PATH: /models/qwen2.5-3b-instruct.Q4_K_M.gguf
      MODEL_PATH: /models/qwen2.5-3b-instruct.Q4_K_M.gguf
    healthcheck:
      test: [ "CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/healthz').read()\"" ]
      interval: 5s
      timeout: 3s
      retries: 20


  bio-service:
    build: ./bio-service
    container_name: plasmic-bio
    environment:
      LLAMA_URL: "http://llama-service:8000"
    ports:
      - "8001:8000"
    depends_on:
       llama-service:
          condition: service_healthy
    volumes:
      - ./bio-service/scripts:/app/scripts:ro
      - ./data:/data:ro

  app:
    build: .
    container_name: plasmic-axum-leptos
    environment:
      LLAMA_URL: "http://llama-service:8000"
      BIO_URL: "http://bio-service:8000"
      DATABASE_URL: "postgres://app_user:app_password@db:5432/app_db"
      LEPTOS_SITE_ADDR: "0.0.0.0:3000"
      RUST_LOG: "info"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      llama-service:
        condition: service_healthy

volumes:
  postgres-data:
